//! Golden corpus harness. Loads the fixtures transcribed from Duckling's EN
//! Time corpus and asserts the Rust parser reproduces each resolved value.
//!
//! Match modes (env `DUCKLING_MATCH`):
//!   contains (default) — expected value is among the full-range Time results
//!   unique             — exactly one full-range Time result, equal to expected
//! `contains` lets rule logic land before the ranker exists; Phase 4 tightens
//! to `unique` (Duckling's real corpus semantics).

use serde_json::Value;

fn load() -> Value {
    let raw = include_str!("../fixtures/en_time_corpus.json");
    serde_json::from_str(raw).expect("fixtures parse")
}

fn ctx() -> duckling::ResolveContext {
    // Test context: civil 2013-02-12 04:30:00 at a fixed -02:00 zone (no transitions).
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let reference = jiff::civil::date(2013, 2, 12)
        .at(4, 30, 0, 0)
        .to_zoned(zone.clone())
        .unwrap()
        .timestamp();
    duckling::ResolveContext {
        reference,
        zone,
        with_latent: false,
    }
}

/// "values" is the alternatives array; behavior-compat ignores it.
fn strip_values(mut v: Value) -> Value {
    if let Value::Object(ref mut o) = v {
        o.remove("values");
    }
    v
}

fn contains_mode() -> bool {
    std::env::var("DUCKLING_MATCH").as_deref() != Ok("unique")
}

fn full_range_time_values(input: &str, ctx: &duckling::ResolveContext) -> Vec<Value> {
    let n = input.chars().count();
    duckling::parse(input, ctx)
        .into_iter()
        .filter(|e| e.dim == "time" && e.start == 0 && e.end == n)
        .map(|e| strip_values(e.value))
        .collect()
}

/// All resolved Time values from the ranked (range-dominated) entities. This is
/// what Duckling's corpus test checks — the best entity, not necessarily one
/// spanning the whole input (e.g. "for a quarter past 3pm" -> "a quarter past
/// 3pm"). Safe: a full-input parse dominates contained sub-ranges, so a *wrong*
/// full parse still surfaces here and fails the check (can't mask a regression).
fn best_time_values(input: &str, ctx: &duckling::ResolveContext) -> Vec<Value> {
    duckling::parse(input, ctx)
        .into_iter()
        .filter(|e| e.dim == "time")
        .map(|e| strip_values(e.value))
        .collect()
}

#[test]
fn positive_corpus() {
    let data = load();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let expected = &ex["expected"];
        if expected.is_null() {
            continue; // long-tail/ambiguous; revisited in Phase 5
        }
        checked += 1;
        let input = ex["input"].as_str().unwrap();
        let got = full_range_time_values(input, &ctx);
        let exp = strip_values(expected.clone());
        let ok = if contains_mode() {
            // Duckling's semantics: expected value among the best (ranked) entities.
            best_time_values(input, &ctx).iter().any(|g| g == &exp)
        } else {
            // unique mode: an unambiguous full-span answer. Redundant rule paths
            // that resolve to the *same* value count as one; only genuinely
            // differing full-span values (real ambiguity) fail.
            !got.is_empty() && got.iter().all(|g| g == &exp)
        };
        if !ok {
            failures.push(format!("{input:?}\n  expected {exp}\n  got      {got:?}"));
        }
    }
    eprintln!("checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(5000)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// DST/timezone correctness — generated by the live oracle against *real* IANA
/// zones (Task 0.6). The corpus is DST-free, so this is the only test that
/// guards offset selection across transitions. Each case carries its own zone
/// + reference instant.
#[test]
fn tz_stress() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/tz_stress.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        let expected = &c["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let zone = jiff::tz::TimeZone::get(c["zone"].as_str().unwrap()).expect("zone");
        let reference: jiff::Timestamp = c["referenceTimeUtc"]
            .as_str()
            .unwrap()
            .parse()
            .expect("reference instant");
        let ctx = duckling::ResolveContext {
            reference,
            zone,
            with_latent: false,
        };
        let got = full_range_time_values(input, &ctx);
        let exp = strip_values(expected.clone());
        if !got.iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {got:?}",
                c["zone"]
            ));
        }
    }
    eprintln!("tz_stress checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} tz-stress failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn negative_corpus() {
    let data = load();
    let ctx = ctx();
    let mut failures = Vec::new();
    for ex in data["negative"].as_array().unwrap() {
        let input = ex.as_str().unwrap();
        let n = full_range_time_values(input, &ctx).len();
        if n != 0 {
            failures.push(format!("{input:?} produced {n} time parses"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} negatives leaked:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Differential test: compositional inputs generated and cross-checked against
/// the live rasa/duckling oracle (DST-free -02:00 context, so oracle values are
/// ground truth). Complements the Corpus.hs-derived positive_corpus by probing
/// rule *combinations* the curated corpus may under-cover. Best-entity semantics.
#[test]
fn differential_corpus() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/differential.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let expected = &ex["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = ex["input"].as_str().unwrap();
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "{input:?}\n  expected {exp}\n  got      {:?}",
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!("differential checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(5000)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Regex rules must not match inside a word: the 3-letter day/month abbreviations
/// (mon, fri, mar, dec, …) are the first letters of many common words. Duckling's
/// token-boundary rule rejects a match that splits a run of same-class chars, so
/// "money"/"friend"/"monkey" yield nothing while whole-word "mon"/"fri" still work.
#[test]
fn no_subword_matches() {
    let ctx = ctx();
    for word in [
        "money", "friend", "market", "monkey", "satisfy", "octopus", "month", "augment", "apron",
        "novel", "decide", "sunny", "monster", "fritter",
    ] {
        let n = duckling::parse(word, &ctx)
            .into_iter()
            .filter(|e| e.dim == "time")
            .count();
        assert_eq!(
            n, 0,
            "{word:?} must not produce a sub-word time match, got {n}"
        );
    }
    // Whole-word abbreviations still resolve.
    for (w, want) in [
        ("mon", "2013-02-18"),
        ("fri", "2013-02-15"),
        ("mar", "2013-03-01"),
        ("dec", "2013-12-01"),
        ("see you fri", "2013-02-15"),
    ] {
        assert!(
            best_time_values(w, &ctx)
                .iter()
                .any(|v| v["value"].as_str().is_some_and(|s| s.starts_with(want))),
            "{w:?} should resolve to {want}"
        );
    }
}

/// "May" is latent (it collides with the modal verb "may"): a bare match is
/// dropped in default mode, so "you may go" doesn't yield a spurious May. But it
/// resolves in latent mode, and any composition ("in May", "May 1st") de-latents
/// it. Other months are always concrete. Guards the mkLatent-on-May fix.
#[test]
fn may_is_latent() {
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let reference = jiff::civil::date(2013, 2, 12)
        .at(4, 30, 0, 0)
        .to_zoned(zone.clone())
        .unwrap()
        .timestamp();
    let default = duckling::ResolveContext {
        reference,
        zone: zone.clone(),
        with_latent: false,
    };
    let latent = duckling::ResolveContext {
        reference,
        zone,
        with_latent: true,
    };

    // Bare "May" / "may 2015": no time entity in default mode (latent, dropped).
    for bare in ["May", "may", "may 2015"] {
        let got = full_range_time_values(bare, &default);
        assert!(
            got.is_empty(),
            "{bare:?} should be latent (no default-mode parse), got {got:?}"
        );
    }
    // In latent mode, bare "May" resolves to May 1st.
    assert!(
        best_time_values("May", &latent)
            .iter()
            .any(|v| v["value"] == "2013-05-01T00:00:00.000-02:00"),
        "May should resolve to 2013-05-01 in latent mode"
    );
    // Composition de-latents it (default mode resolves).
    for (input, want) in [
        ("in May", "2013-05-01"),
        ("May 1st", "2013-05-01"),
        ("next May", "2013-05-01"),
    ] {
        let got = best_time_values(input, &default);
        assert!(
            got.iter()
                .any(|v| v["value"].as_str().is_some_and(|s| s.starts_with(want))),
            "{input:?} should de-latent to {want}, got {got:?}"
        );
    }
    // A concrete month (March) is never latent — present in default mode.
    assert!(
        !full_range_time_values("March", &default).is_empty(),
        "March must not be latent"
    );
}

/// Timezone ground-truth: the product-critical requirement is correct offsets
/// against authoritative IANA tzdata, NOT merely matching Duckling (whose corpus is
/// DST-blind and whose oracle has a documented DST-boundary quirk). For each
/// (zone, date) this resolves "3pm" with the reference at that date's local noon
/// and asserts the resolved instant's offset equals what Python's zoneinfo assigns
/// to that wall-clock — across 9 real zones spanning both hemispheres' DST.
#[test]
fn tz_truth() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/tz_truth.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let zone = jiff::tz::TimeZone::get(c["zone"].as_str().unwrap()).expect("zone");
        let reference: jiff::Timestamp = c["refUtc"].as_str().unwrap().parse().expect("ref");
        let want = c["expectedOffset"].as_str().unwrap();
        let ctx = duckling::ResolveContext {
            reference,
            zone,
            with_latent: false,
        };
        // "3pm" resolves to the reference date's 15:00 in-zone; its value string
        // ends with the RFC3339 offset the port assigned (e.g. "...15:00.000-04:00").
        let got: Vec<String> = duckling::parse("3pm", &ctx)
            .into_iter()
            .filter(|e| e.dim == "time")
            .filter_map(|e| {
                e.value
                    .get("value")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string())
            })
            .collect();
        let ok = got
            .iter()
            .any(|v| v.len() >= 6 && &v[v.len() - 6..] == want);
        if !ok {
            failures.push(format!(
                "[{} {}] expected offset {want}, got {got:?}",
                c["zone"], c["date"]
            ));
        }
    }
    eprintln!("tz_truth checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} tz-truth failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(200)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// The `values` alternatives array: Duckling returns `value` plus a `values` list
/// of the next occurrences (3 for recurring predicates, 1 for past/single ones).
/// The port now emits this; here we check the full array matches the oracle,
/// element-by-element — including the 12h-ambiguous interleaving ("10:30" →
/// 10:30 / 22:30 / next-day) and holiday/interval alternatives.
#[test]
fn values_array() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/values_array.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let default_ref = jiff::civil::date(2013, 2, 12)
        .at(4, 30, 0, 0)
        .to_zoned(zone.clone())
        .unwrap()
        .timestamp();
    let n_of = |input: &str, c: &duckling::ResolveContext| -> Option<Vec<Value>> {
        // the full-span time entity's `values` array
        let count = input.chars().count();
        duckling::parse(input, c)
            .into_iter()
            .find(|e| e.dim == "time" && e.start == 0 && e.end == count)
            .and_then(|e| e.value.get("values").and_then(|v| v.as_array()).cloned())
    };
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let want = c["values"].as_array().unwrap();
        // Optional per-case reference (for covering / across-reference cases);
        // defaults to the standard 04:30 context.
        let reference = match c.get("ref").and_then(|r| r.as_str()) {
            Some(r) => r.parse().expect("ref"),
            None => default_ref,
        };
        let case_ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        match n_of(input, &case_ctx) {
            Some(got) if got.as_slice() == want.as_slice() => {}
            got => failures.push(format!(
                "{input:?}\n  expected {want:?}\n  got      {got:?}"
            )),
        }
    }
    eprintln!("values_array checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(50)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

fn locale_of(s: &str) -> duckling::Locale {
    match s {
        "EnUs" => duckling::Locale::EnUs,
        "EnGb" => duckling::Locale::EnGb,
        "EnCa" => duckling::Locale::EnCa,
        "EnAu" => duckling::Locale::EnAu,
        "EnNz" => duckling::Locale::EnNz,
        "EnIn" => duckling::Locale::EnIn,
        "EnIe" => duckling::Locale::EnIe,
        "EnZa" => duckling::Locale::EnZa,
        "EnPh" => duckling::Locale::EnPh,
        "EnBz" => duckling::Locale::EnBz,
        "EnJm" => duckling::Locale::EnJm,
        "EnTt" => duckling::Locale::EnTt,
        _ => panic!("unknown locale {s}"),
    }
}

/// Region-specific holidays (GB Guy Fawkes Day, AU ANZAC Day / Melbourne Cup, ZA
/// Heritage Day, …), ported from Duckling's per-region Rules.hs and cross-checked
/// against the oracle (locale=en_XX) across 2013/2015/2018 — so nth-weekday and
/// easter-relative regional holidays are validated year-over-year. Each is resolved
/// via parse_locale in its region. Best-entity semantics; per-case reference.
#[test]
fn region_holidays() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/region_holiday_check.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let locale = locale_of(c["locale"].as_str().unwrap());
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("ref");
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(c["expected"].clone());
        let got: Vec<Value> = duckling::parse_locale(input, &ctx, locale)
            .into_iter()
            .filter(|e| e.dim == "time")
            .map(|e| strip_values(e.value))
            .collect();
        if !got.iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{:?} {}] {input:?}\n  expected {exp}\n  got      {got:?}",
                c["locale"], c["ref"]
            ));
        }
    }
    eprintln!(
        "region_holidays checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(60)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// All English regions' numeric-date conventions vs the oracle (locale=en_XX):
/// month-first (US/CA/PH), day-first (GB/AU/NZ/IN/IE/BZ/JM/TT), and ZA's hybrid
/// (no-year month-first, with-year day-first). null expected = the region rejects
/// that form (out-of-range month field).
#[test]
fn region_dates() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/region_dates.json")).unwrap();
    let ctx = ctx();
    let loc = |s: &str| match s {
        "EnUs" => duckling::Locale::EnUs,
        "EnGb" => duckling::Locale::EnGb,
        "EnCa" => duckling::Locale::EnCa,
        "EnAu" => duckling::Locale::EnAu,
        "EnNz" => duckling::Locale::EnNz,
        "EnIn" => duckling::Locale::EnIn,
        "EnIe" => duckling::Locale::EnIe,
        "EnZa" => duckling::Locale::EnZa,
        "EnPh" => duckling::Locale::EnPh,
        "EnBz" => duckling::Locale::EnBz,
        "EnJm" => duckling::Locale::EnJm,
        "EnTt" => duckling::Locale::EnTt,
        _ => panic!("unknown locale {s}"),
    };
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let locale = loc(c["locale"].as_str().unwrap());
        let count = input.chars().count();
        let got: Vec<Value> = duckling::parse_locale(input, &ctx, locale)
            .into_iter()
            .filter(|e| e.dim == "time" && e.start == 0 && e.end == count)
            .map(|e| strip_values(e.value))
            .collect();
        let expected = &c["expected"];
        let ok = if expected.is_null() {
            got.is_empty()
        } else {
            got.iter().any(|g| g == &strip_values(expected.clone()))
        };
        if !ok {
            failures.push(format!(
                "[{:?}] {input:?}\n  expected {expected}\n  got      {got:?}",
                c["locale"]
            ));
        }
    }
    eprintln!("region_dates checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// EN_GB locale: numeric dates are day-first (dd/mm), unlike the US default
/// (mm/dd). Cross-checked against the oracle with locale=en_GB. Positive cases
/// resolve day-first ("13/12/2013"→Dec 13, "3/4/2015"→Apr 3); rejections are
/// day-first forms whose month field is out of range ("6/15/2014", "2/29/2016").
#[test]
fn gb_locale() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/gb_locale.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let count = input.chars().count();
        let got: Vec<Value> = duckling::parse_locale(input, &ctx, duckling::Locale::EnGb)
            .into_iter()
            .filter(|e| e.dim == "time" && e.start == 0 && e.end == count)
            .map(|e| strip_values(e.value))
            .collect();
        let expected = &c["expected"];
        let ok = if expected.is_null() {
            got.is_empty()
        } else {
            got.iter().any(|g| g == &strip_values(expected.clone()))
        };
        if !ok {
            failures.push(format!(
                "{input:?}\n  expected {expected}\n  got      {got:?}"
            ));
        }
    }
    eprintln!("gb_locale checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Beyond-Duckling extension: holidays absent from Duckling's frozen (~2020-03)
/// data — introduced/renamed since (US Juneteenth National Independence Day,
/// CA Truth and Reconciliation / Orange Shirt / Emancipation / National
/// Indigenous Peoples Day, NZ Matariki + King's Birthday rename, IE St Brigid's
/// Day) or simply never included (AU Queen's/King's Birthday). These DELIBERATELY
/// diverge from the oracle, which returns nothing for them; expected values are
/// hand-authored against official government dates. Region-scoped, so they never
/// leak into oracle-based region tests. An optional per-case "ref" pins the
/// reference (default = ctx()'s 2013-02-12) — used to lock the legislated
/// date-table years for Matariki / St Brigid's Day. See docs/RUST_PORT_PROGRESS.md.
#[test]
fn modern_holidays() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/modern_holidays.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let default_ref = ctx().reference;
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let locale = locale_of(c["locale"].as_str().unwrap());
        let reference = match c.get("ref").and_then(|v| v.as_str()) {
            Some(s) => s.parse().expect("ref"),
            None => default_ref,
        };
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(c["expected"].clone());
        let got: Vec<Value> = duckling::parse_locale(input, &ctx, locale)
            .into_iter()
            .filter(|e| e.dim == "time")
            .map(|e| strip_values(e.value))
            .collect();
        if !got.iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{:?}] {input:?}\n  expected {exp}\n  got      {got:?}",
                c["locale"]
            ));
        }
    }
    eprintln!(
        "modern_holidays checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// ASR / spoken-English time idioms — the actual input distribution of a
/// speech pipeline ("half seven", "eight oh five am", "the fifteenth of august",
/// "december twenty fifth", "quarter to noon", "the day after tomorrow", …).
/// Each was cross-checked against the live oracle (en_US, ref 2013-02-12 04:30);
/// only cases the oracle resolves are kept. Expected values are offset-stripped
/// wall-clock (the port's -02:00 output compared against the oracle's UTC
/// wall-clock, both from a 04:30 reference). This surfaced — and now guards —
/// the written-ordinal gap (first..tenth only) and the "<hour> oh <minute>" gap.
#[test]
fn spoken_forms() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/spoken_forms.json")).unwrap();
    let ctx = ctx();
    // Strip a trailing tz offset ("...-02:00" / "...Z" / "...+00:00") to leave wall-clock.
    fn wall(s: &str) -> String {
        let s = s.trim();
        match s
            .rfind('Z')
            .or_else(|| s.rfind('+'))
            .or_else(|| s.rfind('-').filter(|&i| i > 10))
        {
            Some(i) => s[..i].to_string(),
            None => s.to_string(),
        }
    }
    fn port_walls(input: &str, ctx: &duckling::ResolveContext) -> Vec<String> {
        duckling::parse(input, ctx)
            .into_iter()
            .filter(|e| e.dim == "time")
            .map(|e| {
                let v = &e.value;
                if let Some(val) = v.get("value").and_then(|x| x.as_str()) {
                    wall(val)
                } else {
                    format!(
                        "[{}|{}]",
                        v.get("from")
                            .and_then(|f| f.get("value"))
                            .and_then(|x| x.as_str())
                            .map(wall)
                            .unwrap_or("None".into()),
                        v.get("to")
                            .and_then(|f| f.get("value"))
                            .and_then(|x| x.as_str())
                            .map(wall)
                            .unwrap_or("None".into())
                    )
                }
            })
            .collect()
    }
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let exp = c["wall"].as_str().unwrap().to_string();
        let got = port_walls(input, &ctx);
        if !got.iter().any(|g| g == &exp) {
            failures.push(format!("{input:?}\n  expected {exp}\n  got      {got:?}"));
        }
    }
    eprintln!("spoken_forms checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Duration dimension (`parse_duration`) — port of Duckling/Duration/EN/Corpus.hs.
/// Each case's full-span duration entity must carry the expected `value`+`unit`,
/// and its `normalized.value` (seconds) must match `inSeconds(unit, value)`.
/// Negatives must produce no full-span duration entity. Duration resolution is
/// context-free, so no ResolveContext is used.
#[test]
fn duration_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/duration_corpus.json")).unwrap();
    let per_second = |u: &str| -> i64 {
        match u {
            "second" => 1,
            "minute" => 60,
            "hour" => 3600,
            "day" => 86400,
            "week" => 604800,
            "month" => 2_592_000,
            "quarter" => 7_776_000,
            "year" => 31_536_000,
            _ => panic!("unit {u}"),
        }
    };
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let n = input.chars().count();
        let want_val = c["value"].as_i64().unwrap();
        let want_unit = c["unit"].as_str().unwrap();
        let want_norm = per_second(want_unit) * want_val;
        let got: Vec<Value> = duckling::parse_duration(input)
            .into_iter()
            .filter(|e| e.dim == "duration" && e.start == 0 && e.end == n)
            .map(|e| e.value)
            .collect();
        let ok = got.iter().any(|v| {
            v["value"].as_i64() == Some(want_val)
                && v["unit"].as_str() == Some(want_unit)
                && v["normalized"]["value"].as_i64() == Some(want_norm)
        });
        if !ok {
            failures.push(format!("{input:?}\n  expected {want_val} {want_unit} (norm {want_norm})\n  got      {got:?}"));
        }
    }
    // Negatives: no full-span duration entity.
    for neg in data["negatives"].as_array().unwrap() {
        checked += 1;
        let input = neg.as_str().unwrap();
        let n = input.chars().count();
        let hit: Vec<Value> = duckling::parse_duration(input)
            .into_iter()
            .filter(|e| e.dim == "duration" && e.start == 0 && e.end == n)
            .map(|e| e.value)
            .collect();
        if !hit.is_empty() {
            failures.push(format!("[negative] {input:?} unexpectedly parsed: {hit:?}"));
        }
    }
    eprintln!(
        "duration_corpus checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Ordinal dimension (`parse_ordinal`) — port of Duckling/Ordinal/EN/Corpus.hs.
/// Each case's full-span ordinal entity must carry the expected integer value.
/// Directly validates the composite-ordinal port ("twenty-fifth", "thirtyfirst",
/// em-dash/space/concatenated separators) against Duckling, not just via Time.
#[test]
fn ordinal_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/ordinal_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let n = input.chars().count();
        let want = c["value"].as_i64().unwrap();
        let got: Vec<i64> = duckling::parse_ordinal(input)
            .into_iter()
            .filter(|e| e.dim == "ordinal" && e.start == 0 && e.end == n)
            .filter_map(|e| e.value["value"].as_i64())
            .collect();
        if !got.contains(&want) {
            failures.push(format!("{input:?}\n  expected {want}\n  got      {got:?}"));
        }
    }
    eprintln!(
        "ordinal_corpus checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Numeral dimension (`parse_numeral`) — the supported subset of
/// Duckling/Numeral/EN/Corpus.hs (integers, written numbers, informal
/// quantifiers, compounds). Decimals/negatives/fractions/magnitude-suffixes are
/// deferred (see docs/REMAINING_DIMENSIONS.md), so they are not asserted here.
#[test]
fn numeral_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/numeral_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let n = input.chars().count();
        let want = c["value"].as_i64().unwrap();
        let got: Vec<i64> = duckling::parse_numeral(input)
            .into_iter()
            .filter(|e| e.dim == "number" && e.start == 0 && e.end == n)
            .filter_map(|e| e.value["value"].as_i64())
            .collect();
        if !got.contains(&want) {
            failures.push(format!("{input:?}\n  expected {want}\n  got      {got:?}"));
        }
    }
    eprintln!(
        "numeral_corpus checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Email dimension (`parse_email`) — port of Duckling/Email/EN/Corpus.hs. A
/// positive must produce an entity whose value equals the expected address
/// (literal and spelled-out "a at b dot com" forms); negatives produce none.
#[test]
fn email_corpus() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/email_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let want = c["value"].as_str().unwrap();
        let got: Vec<String> = duckling::parse_email(input)
            .into_iter()
            .filter_map(|e| e.value["value"].as_str().map(str::to_string))
            .collect();
        if !got.iter().any(|g| g == want) {
            failures.push(format!("{input:?}\n  expected {want}\n  got      {got:?}"));
        }
    }
    for neg in data["negatives"].as_array().unwrap() {
        checked += 1;
        let input = neg.as_str().unwrap();
        let hit = duckling::parse_email(input);
        if !hit.is_empty() {
            failures.push(format!(
                "[negative] {input:?} parsed: {:?}",
                hit.iter()
                    .map(|e| e.value["value"].clone())
                    .collect::<Vec<_>>()
            ));
        }
    }
    eprintln!("email_corpus checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Url dimension (`parse_url`) — port of Duckling/Url/Rules.hs. A positive must
/// produce an entity with the expected value + (lowercased) domain; negatives
/// (bare words, "hey:42", …) produce none.
#[test]
fn url_corpus() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/url_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let (wv, wd) = (c["value"].as_str().unwrap(), c["domain"].as_str().unwrap());
        let ok = duckling::parse_url(input).iter().any(|e| {
            e.value["value"].as_str() == Some(wv) && e.value["domain"].as_str() == Some(wd)
        });
        if !ok {
            let got: Vec<_> = duckling::parse_url(input)
                .into_iter()
                .map(|e| e.value)
                .collect();
            failures.push(format!(
                "{input:?}\n  expected ({wv}, {wd})\n  got      {got:?}"
            ));
        }
    }
    for neg in data["negatives"].as_array().unwrap() {
        checked += 1;
        let input = neg.as_str().unwrap();
        if !duckling::parse_url(input).is_empty() {
            failures.push(format!("[negative] {input:?} parsed a URL"));
        }
    }
    eprintln!("url_corpus checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// CreditCardNumber dimension (`parse_creditcard`) — port of
/// Duckling/CreditCardNumber. A positive must produce an entity with the
/// expected digits-only value + issuer (dashed and undashed forms); negatives
/// (Luhn/length failures, non-numbers) produce none.
#[test]
fn creditcard_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/creditcard_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let (wv, wi) = (c["value"].as_str().unwrap(), c["issuer"].as_str().unwrap());
        let ok = duckling::parse_creditcard(input).iter().any(|e| {
            e.value["value"].as_str() == Some(wv) && e.value["issuer"].as_str() == Some(wi)
        });
        if !ok {
            let got: Vec<_> = duckling::parse_creditcard(input)
                .into_iter()
                .map(|e| e.value)
                .collect();
            failures.push(format!(
                "{input:?}\n  expected ({wv}, {wi})\n  got      {got:?}"
            ));
        }
    }
    for neg in data["negatives"].as_array().unwrap() {
        checked += 1;
        let input = neg.as_str().unwrap();
        if !duckling::parse_creditcard(input).is_empty() {
            failures.push(format!("[negative] {input:?} parsed a card"));
        }
    }
    eprintln!(
        "creditcard_corpus checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// PhoneNumber dimension (`parse_phonenumber`) — port of
/// Duckling/PhoneNumber/Corpus.hs. A positive must produce an entity whose value
/// equals the normalized "(+<code>) <digits> ext <ext>" string; negatives
/// (too short / too long) produce none.
#[test]
fn phonenumber_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/phonenumber_corpus.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let want = c["value"].as_str().unwrap();
        let got: Vec<String> = duckling::parse_phonenumber(input)
            .into_iter()
            .filter_map(|e| e.value["value"].as_str().map(str::to_string))
            .collect();
        if !got.iter().any(|g| g == want) {
            failures.push(format!("{input:?}\n  expected {want}\n  got      {got:?}"));
        }
    }
    for neg in data["negatives"].as_array().unwrap() {
        checked += 1;
        let input = neg.as_str().unwrap();
        if !duckling::parse_phonenumber(input).is_empty() {
            failures.push(format!("[negative] {input:?} parsed a phone number"));
        }
    }
    eprintln!(
        "phonenumber_corpus checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Combined Time+Duration (`parse_all`) — the `dims:["time","duration"]` surface.
/// Time and Duration compete in one pool by dimension-agnostic range domination,
/// exactly as Duckling: the widest match per position wins, disjoint matches all
/// surface. Each case's expected surviving entities (as (dim, start, end)) were
/// captured from the live oracle. Verifies e.g. "in 2 hours"→one Time (contained
/// "2 hours" Duration dominated), "…20 minutes and wake me at 7am"→Duration+Time.
#[test]
fn combined_dims() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/combined_dims.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let mut exp: Vec<(String, u64, u64)> = c["expected"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                (
                    e[0].as_str().unwrap().to_string(),
                    e[1].as_u64().unwrap(),
                    e[2].as_u64().unwrap(),
                )
            })
            .collect();
        exp.sort();
        let mut got: Vec<(String, u64, u64)> = duckling::parse_all(input, &ctx)
            .into_iter()
            .map(|e| (e.dim, e.start as u64, e.end as u64))
            .collect();
        got.sort();
        if exp != got {
            failures.push(format!("{input:?}\n  expected {exp:?}\n  got      {got:?}"));
        }
    }
    eprintln!(
        "combined_dims checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Large-scale randomized differential: random inputs (from parameterized
/// templates across every rule family) paired with random references (date +
/// time-of-day, 2010–2022), cross-checked against the oracle. All prior fuzzing
/// varied inputs OR references; this varies both together at scale (1500 cases)
/// to catch rare interaction bugs the separate audits couldn't. Best-entity.
#[test]
fn random_diff() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/random_diff.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("ref");
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(c["expected"].clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {:?}",
                c["ref"],
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!("random_diff checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(60)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Robustness: adversarial / untrusted input must never panic or hang. Huge
/// magnitudes blew up two ways — jiff's Span setters panic above their per-unit
/// range (fixed: fallible `try_*` in grain::add), and predNth/predNthAfter walked
/// an infinite series `take(n+2)` times for absurd n (fixed: MAX_NTH cap). A panic
/// fails this test outright; a regression that reintroduces the hang would time out.
#[test]
fn robustness() {
    let ctx = ctx();
    let adversarial = [
        "999999999999999999 days ago",
        "in 9999999999999 years",
        "in 99999999 months",
        "in 2147483648 days",
        "9999999999 hours ago",
        "1000000 months from now",
        "in 100000000 days",
        "50000 years from now",
        "in 9999999999999999 minutes",
        "9999999999999999999 fridays from now",
        "in 5000000000 quarters",
        "in 88888888888 fortnights",
        "the 999999999999th of january",
        "2222222222222-02-12",
        "999999999th monday",
        "february 31",
        "2013-99-99",
        "99:99",
        "year 999999999999",
        "the 32nd",
        "in -5 days",
        "in 0 days",
        "",
        "   ",
        "!@#$%^&*()",
        "\u{1f600} tomorrow",
    ];
    for input in adversarial {
        // Must return (no panic); content is irrelevant.
        let _ = duckling::parse(input, &ctx);
    }
    // Legitimately-large N must still resolve (the cap is generous, not restrictive).
    assert!(
        best_time_values("500 fridays from now", &ctx)
            .iter()
            .any(|v| v["value"] == "2022-09-09T00:00:00.000-02:00"),
        "500 fridays from now should still resolve"
    );
}

/// Reference time-of-day: time-sensitive inputs ("3pm", "this morning", "in 2
/// hours", "tonight") resolved at 10 reference times across a single day (00:30 →
/// 23:30), vs the oracle. Every other test fixes the reference at 04:30, so the
/// past/future/rollover logic when a target time has already passed today (e.g.
/// "9am" at 15:00 → tomorrow) is otherwise untested. Best-entity semantics.
#[test]
fn tod_ref() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/tod_ref.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("ref");
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(c["expected"].clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "[@{}] {input:?}\n  expected {exp}\n  got      {:?}",
                c["refLabel"],
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!("tod_ref checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(200)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Holidays across years: every holiday the port knows, resolved at reference =
/// Jan 1 of each year 2013–2020, checked against the oracle. The corpus only tests
/// holidays at one reference year (2013); the *computed* holidays (Easter-relative,
/// Islamic/Hindu/Jewish lunar) shift yearly via date tables/algorithms, so a table
/// error in another year would otherwise go undetected. Best-entity semantics.
#[test]
fn holiday_years() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/holiday_years.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("ref");
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(c["expected"].clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {:?}",
                c["year"],
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!(
        "holiday_years checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(200)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// DST gap/fold ground-truth: the hardest offset case. A spring-forward gap time
/// (2:30am, nonexistent) and a fall-back fold time (1:30am, repeated) are ambiguous;
/// the port resolves them by picking the pre-transition ("before") offset. This
/// asserts that choice matches Python zoneinfo's PEP-495 fold=0 convention across
/// 12 real 2013 transitions (US/EU/AU/NZ). Ground truth, not Duckling.
#[test]
fn tz_gapfold() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/tz_gapfold.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let zone = jiff::tz::TimeZone::get(c["zone"].as_str().unwrap()).expect("zone");
        let reference: jiff::Timestamp = c["refUtc"].as_str().unwrap().parse().expect("ref");
        let input = c["input"].as_str().unwrap();
        let want = c["expectedOffset"].as_str().unwrap();
        let ctx = duckling::ResolveContext {
            reference,
            zone,
            with_latent: false,
        };
        let got: Vec<String> = duckling::parse(input, &ctx)
            .into_iter()
            .filter(|e| e.dim == "time")
            .filter_map(|e| {
                e.value
                    .get("value")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_string())
            })
            .collect();
        let ok = got
            .iter()
            .any(|v| v.len() >= 6 && &v[v.len() - 6..] == want);
        if !ok {
            failures.push(format!(
                "[{} {} {}] {input:?} expected offset {want}, got {got:?}",
                c["zone"], c["date"], c["kind"]
            ));
        }
    }
    eprintln!("tz_gapfold checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} gap/fold failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Multi-entity extraction: inputs with several times ("Monday or Tuesday",
/// "9am Monday and 5pm Friday") where the ranker must select multiple non-
/// overlapping best entities. Prior tests only checked the single best entity;
/// this compares the *full set* of (start, end, value) against the oracle.
#[test]
fn multi_entity() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/multi_entity.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        checked += 1;
        let input = c["input"].as_str().unwrap();
        // Expected set of (start, end, value) from the oracle.
        let mut want: Vec<(u64, u64, Value)> = c["entities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                (
                    e["start"].as_u64().unwrap(),
                    e["end"].as_u64().unwrap(),
                    strip_values(e["value"].clone()),
                )
            })
            .collect();
        want.sort_by_key(|(s, e, _)| (*s, *e));
        // Port's set.
        let mut got: Vec<(u64, u64, Value)> = duckling::parse(input, &ctx)
            .into_iter()
            .filter(|e| e.dim == "time")
            .map(|e| (e.start as u64, e.end as u64, strip_values(e.value)))
            .collect();
        got.sort_by_key(|(s, e, _)| (*s, *e));
        if got != want {
            failures.push(format!(
                "{input:?}\n  expected {want:?}\n  got      {got:?}"
            ));
        }
    }
    eprintln!("multi_entity checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(5000)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Sentence-level differential: natural sentences with an embedded time expression
/// ("Can we meet next Tuesday afternoon?", "I need money by friday"), cross-checked
/// against the oracle. Tests span extraction + ranking within surrounding words —
/// the realistic free-text case the bare-input corpus doesn't cover. Best-entity.
#[test]
fn sentence_stress() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/sentence_stress.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let input = ex["input"].as_str().unwrap();
        let expected = &ex["expected"];
        checked += 1;
        if expected.is_null() {
            // Oracle finds no time in this sentence — the port must not either
            // (false-positive guard: "I have 3 dogs", "we may go later").
            let got = best_time_values(input, &ctx);
            if !got.is_empty() {
                failures.push(format!("{input:?}\n  expected NO time\n  got      {got:?}"));
            }
            continue;
        }
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "{input:?}\n  expected {exp}\n  got      {:?}",
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!(
        "sentence_stress checked {checked}, {} failing",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(5000)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Reference-time differential: ref-sensitive inputs ("next tuesday", "end of the
/// month", "in 3 days") cross-checked against the oracle across many reference
/// instants (varied weekdays, month/year boundaries, leap days), all in the fixed
/// -02:00 zone. The fixed-ref corpus/differential can't catch reference-dependent
/// bugs (e.g. "this tuesday at 3" only broke when the reference day was Tuesday).
/// Best-entity semantics; each case carries its own reference.
#[test]
fn ref_stress() {
    let data: Value = serde_json::from_str(include_str!("../fixtures/ref_stress.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        let expected = &c["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("reference");
        let ctx = duckling::ResolveContext {
            reference,
            zone: zone.clone(),
            with_latent: false,
        };
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {:?}",
                c["refLabel"],
                best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!("ref_stress checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures
            .iter()
            .take(5000)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
