//! Golden corpus harness. Loads the fixtures transcribed from Duckling's EN
//! Time corpus and asserts the Rust parser reproduces each resolved value.
//!
//! Match modes (env `DUCKLING_MATCH`):
//!   contains (default) — expected value is among the full-range Time results
//!   unique             — exactly one full-range Time result, equal to expected
//! `contains` lets rule logic land before the ranker exists; Phase 4 tightens
//! to `unique` (Duckling's real corpus semantics).

use serde_json::Value;

fn load() -> Value {
    let raw = include_str!("../fixtures/en_time_corpus.json");
    serde_json::from_str(raw).expect("fixtures parse")
}

fn ctx() -> duckling::ResolveContext {
    // Test context: civil 2013-02-12 04:30:00 at a fixed -02:00 zone (no transitions).
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let reference = jiff::civil::date(2013, 2, 12)
        .at(4, 30, 0, 0)
        .to_zoned(zone.clone())
        .unwrap()
        .timestamp();
    duckling::ResolveContext { reference, zone, with_latent: false }
}

/// "values" is the alternatives array; behavior-compat ignores it.
fn strip_values(mut v: Value) -> Value {
    if let Value::Object(ref mut o) = v {
        o.remove("values");
    }
    v
}

fn contains_mode() -> bool {
    std::env::var("DUCKLING_MATCH").as_deref() != Ok("unique")
}

fn full_range_time_values(input: &str, ctx: &duckling::ResolveContext) -> Vec<Value> {
    let n = input.chars().count();
    duckling::parse(input, ctx)
        .into_iter()
        .filter(|e| e.dim == "time" && e.start == 0 && e.end == n)
        .map(|e| strip_values(e.value))
        .collect()
}

/// All resolved Time values from the ranked (range-dominated) entities. This is
/// what Duckling's corpus test checks — the best entity, not necessarily one
/// spanning the whole input (e.g. "for a quarter past 3pm" -> "a quarter past
/// 3pm"). Safe: a full-input parse dominates contained sub-ranges, so a *wrong*
/// full parse still surfaces here and fails the check (can't mask a regression).
fn best_time_values(input: &str, ctx: &duckling::ResolveContext) -> Vec<Value> {
    duckling::parse(input, ctx)
        .into_iter()
        .filter(|e| e.dim == "time")
        .map(|e| strip_values(e.value))
        .collect()
}

#[test]
fn positive_corpus() {
    let data = load();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let expected = &ex["expected"];
        if expected.is_null() {
            continue; // long-tail/ambiguous; revisited in Phase 5
        }
        checked += 1;
        let input = ex["input"].as_str().unwrap();
        let got = full_range_time_values(input, &ctx);
        let exp = strip_values(expected.clone());
        let ok = if contains_mode() {
            // Duckling's semantics: expected value among the best (ranked) entities.
            best_time_values(input, &ctx).iter().any(|g| g == &exp)
        } else {
            // unique mode: an unambiguous full-span answer. Redundant rule paths
            // that resolve to the *same* value count as one; only genuinely
            // differing full-span values (real ambiguity) fail.
            !got.is_empty() && got.iter().all(|g| g == &exp)
        };
        if !ok {
            failures.push(format!("{input:?}\n  expected {exp}\n  got      {got:?}"));
        }
    }
    eprintln!("checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} failures:\n{}",
        failures.len(),
        failures.iter().take(5000).cloned().collect::<Vec<_>>().join("\n")
    );
}

/// DST/timezone correctness — generated by the live oracle against *real* IANA
/// zones (Task 0.6). The corpus is DST-free, so this is the only test that
/// guards offset selection across transitions. Each case carries its own zone
/// + reference instant.
#[test]
fn tz_stress() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/tz_stress.json")).unwrap();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        let expected = &c["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let zone = jiff::tz::TimeZone::get(c["zone"].as_str().unwrap()).expect("zone");
        let reference: jiff::Timestamp =
            c["referenceTimeUtc"].as_str().unwrap().parse().expect("reference instant");
        let ctx = duckling::ResolveContext { reference, zone, with_latent: false };
        let got = full_range_time_values(input, &ctx);
        let exp = strip_values(expected.clone());
        if !got.iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {got:?}",
                c["zone"]
            ));
        }
    }
    eprintln!("tz_stress checked {checked}, {} failing", failures.len());
    assert!(
        failures.is_empty(),
        "{} tz-stress failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn negative_corpus() {
    let data = load();
    let ctx = ctx();
    let mut failures = Vec::new();
    for ex in data["negative"].as_array().unwrap() {
        let input = ex.as_str().unwrap();
        let n = full_range_time_values(input, &ctx).len();
        if n != 0 {
            failures.push(format!("{input:?} produced {n} time parses"));
        }
    }
    assert!(
        failures.is_empty(),
        "{} negatives leaked:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// Differential test: compositional inputs generated and cross-checked against
/// the live rasa/duckling oracle (DST-free -02:00 context, so oracle values are
/// ground truth). Complements the Corpus.hs-derived positive_corpus by probing
/// rule *combinations* the curated corpus may under-cover. Best-entity semantics.
#[test]
fn differential_corpus() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/differential.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let expected = &ex["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = ex["input"].as_str().unwrap();
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!("{input:?}\n  expected {exp}\n  got      {:?}", best_time_values(input, &ctx)));
        }
    }
    eprintln!("differential checked {checked}, {} failing", failures.len());
    assert!(failures.is_empty(), "{} failures:\n{}", failures.len(),
        failures.iter().take(5000).cloned().collect::<Vec<_>>().join("\n"));
}

/// Regex rules must not match inside a word: the 3-letter day/month abbreviations
/// (mon, fri, mar, dec, …) are the first letters of many common words. Duckling's
/// token-boundary rule rejects a match that splits a run of same-class chars, so
/// "money"/"friend"/"monkey" yield nothing while whole-word "mon"/"fri" still work.
#[test]
fn no_subword_matches() {
    let ctx = ctx();
    for word in [
        "money", "friend", "market", "monkey", "satisfy", "octopus", "month",
        "augment", "apron", "novel", "decide", "sunny", "monster", "fritter",
    ] {
        let n = duckling::parse(word, &ctx).into_iter().filter(|e| e.dim == "time").count();
        assert_eq!(n, 0, "{word:?} must not produce a sub-word time match, got {n}");
    }
    // Whole-word abbreviations still resolve.
    for (w, want) in [("mon", "2013-02-18"), ("fri", "2013-02-15"), ("mar", "2013-03-01"),
                      ("dec", "2013-12-01"), ("see you fri", "2013-02-15")] {
        assert!(best_time_values(w, &ctx).iter().any(|v| v["value"].as_str().is_some_and(|s| s.starts_with(want))),
            "{w:?} should resolve to {want}");
    }
}

/// "May" is latent (it collides with the modal verb "may"): a bare match is
/// dropped in default mode, so "you may go" doesn't yield a spurious May. But it
/// resolves in latent mode, and any composition ("in May", "May 1st") de-latents
/// it. Other months are always concrete. Guards the mkLatent-on-May fix.
#[test]
fn may_is_latent() {
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let reference = jiff::civil::date(2013, 2, 12).at(4, 30, 0, 0)
        .to_zoned(zone.clone()).unwrap().timestamp();
    let default = duckling::ResolveContext { reference, zone: zone.clone(), with_latent: false };
    let latent = duckling::ResolveContext { reference, zone, with_latent: true };

    // Bare "May" / "may 2015": no time entity in default mode (latent, dropped).
    for bare in ["May", "may", "may 2015"] {
        let got = full_range_time_values(bare, &default);
        assert!(got.is_empty(), "{bare:?} should be latent (no default-mode parse), got {got:?}");
    }
    // In latent mode, bare "May" resolves to May 1st.
    assert!(
        best_time_values("May", &latent).iter().any(|v| v["value"] == "2013-05-01T00:00:00.000-02:00"),
        "May should resolve to 2013-05-01 in latent mode"
    );
    // Composition de-latents it (default mode resolves).
    for (input, want) in [("in May", "2013-05-01"), ("May 1st", "2013-05-01"), ("next May", "2013-05-01")] {
        let got = best_time_values(input, &default);
        assert!(got.iter().any(|v| v["value"].as_str().is_some_and(|s| s.starts_with(want))),
            "{input:?} should de-latent to {want}, got {got:?}");
    }
    // A concrete month (March) is never latent — present in default mode.
    assert!(!full_range_time_values("March", &default).is_empty(), "March must not be latent");
}

/// Sentence-level differential: natural sentences with an embedded time expression
/// ("Can we meet next Tuesday afternoon?", "I need money by friday"), cross-checked
/// against the oracle. Tests span extraction + ranking within surrounding words —
/// the realistic free-text case the bare-input corpus doesn't cover. Best-entity.
#[test]
fn sentence_stress() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/sentence_stress.json")).unwrap();
    let ctx = ctx();
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for ex in data["positive"].as_array().unwrap() {
        let input = ex["input"].as_str().unwrap();
        let expected = &ex["expected"];
        checked += 1;
        if expected.is_null() {
            // Oracle finds no time in this sentence — the port must not either
            // (false-positive guard: "I have 3 dogs", "we may go later").
            let got = best_time_values(input, &ctx);
            if !got.is_empty() {
                failures.push(format!("{input:?}\n  expected NO time\n  got      {got:?}"));
            }
            continue;
        }
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!("{input:?}\n  expected {exp}\n  got      {:?}", best_time_values(input, &ctx)));
        }
    }
    eprintln!("sentence_stress checked {checked}, {} failing", failures.len());
    assert!(failures.is_empty(), "{} failures:\n{}", failures.len(),
        failures.iter().take(5000).cloned().collect::<Vec<_>>().join("\n"));
}

/// Reference-time differential: ref-sensitive inputs ("next tuesday", "end of the
/// month", "in 3 days") cross-checked against the oracle across many reference
/// instants (varied weekdays, month/year boundaries, leap days), all in the fixed
/// -02:00 zone. The fixed-ref corpus/differential can't catch reference-dependent
/// bugs (e.g. "this tuesday at 3" only broke when the reference day was Tuesday).
/// Best-entity semantics; each case carries its own reference.
#[test]
fn ref_stress() {
    let data: Value =
        serde_json::from_str(include_str!("../fixtures/ref_stress.json")).unwrap();
    let zone = jiff::tz::TimeZone::fixed(jiff::tz::Offset::constant(-2));
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for c in data["cases"].as_array().unwrap() {
        let expected = &c["expected"];
        if expected.is_null() {
            continue;
        }
        checked += 1;
        let input = c["input"].as_str().unwrap();
        let reference: jiff::Timestamp = c["ref"].as_str().unwrap().parse().expect("reference");
        let ctx = duckling::ResolveContext { reference, zone: zone.clone(), with_latent: false };
        let exp = strip_values(expected.clone());
        if !best_time_values(input, &ctx).iter().any(|g| g == &exp) {
            failures.push(format!(
                "[{}] {input:?}\n  expected {exp}\n  got      {:?}",
                c["refLabel"], best_time_values(input, &ctx)
            ));
        }
    }
    eprintln!("ref_stress checked {checked}, {} failing", failures.len());
    assert!(failures.is_empty(), "{} failures:\n{}", failures.len(),
        failures.iter().take(5000).cloned().collect::<Vec<_>>().join("\n"));
}
